import type { Metadata } from 'next';

import { Toaster } from 'react-hot-toast';

import GlobalStyles from '@/libs/foundations/global-styles';
import StyledComponentsRegistry from '@/libs/hoc/style-components';
import { ThemeProvider } from '@/libs/hoc/theme';
import { LayoutWrapper } from '@/libs/components/atoms';
import { ThemeSwitcher } from '@/libs/components/molecules';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body>
          <ThemeProvider>
            <GlobalStyles />
            <LayoutWrapper>{children}</LayoutWrapper>
            <ThemeSwitcher />
            <Toaster position="bottom-center" />
          </ThemeProvider>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
